import { Task, ItineraryItem } from "../types";

export interface GoogleCalendarEvent {
  summary: string;
  description: string;
  start: {
    dateTime: string;
    timeZone?: string;
  };
  end: {
    dateTime: string;
    timeZone?: string;
  };
  reminders?: {
    useDefault: boolean;
    overrides?: Array<{
      method: "popup" | "email";
      minutes: number;
    }>;
  };
  colorId?: string;
}

/**
 * Validates and normalizes any ISO string or date string.
 * Falls back to a safe date if invalid.
 */
export function ensureValidISOString(dateStr: string, fallbackOffsetHours = 0): string {
  try {
    const d = new Date(dateStr);
    if (!isNaN(d.getTime())) {
      return d.toISOString();
    }
  } catch (e) {
    console.warn("Invalid date encountered, falling back:", dateStr);
  }
  
  // Safe mock fallback date for the application context: 2026-06-24
  const fallback = new Date("2026-06-24T09:00:00-07:00");
  fallback.setHours(fallback.getHours() + fallbackOffsetHours);
  return fallback.toISOString();
}

/**
 * Transforms a Task object into a Google Calendar Event structure.
 * Ensures start/end compatibility, proper duration, and priority mapping.
 * 
 * @param task The task to transform
 * @param timeZone Optional IANA time zone identifier (defaults to "America/Los_Angeles" for consistency)
 * @returns GoogleCalendarEvent
 */
export function transformTaskToCalendarEvent(
  task: Task,
  timeZone = "America/Los_Angeles"
): GoogleCalendarEvent {
  // Validate and parse the deadline
  const endISO = ensureValidISOString(task.deadline, 4);
  const endDate = new Date(endISO);
  
  // Start time is estimatedMinutes before the deadline (so user has a dedicated block to finish it)
  const durationMinutes = Math.max(10, task.estimatedMinutes || 30);
  const startDate = new Date(endDate.getTime() - durationMinutes * 60 * 1000);
  const startISO = startDate.toISOString();

  // Set descriptive priority emoji
  let priorityEmoji = "📝";
  let colorId = "1"; // Lavender (Default / Low)
  
  if (task.priority === "high") {
    priorityEmoji = "🚨";
    colorId = "11"; // Tomato (Red)
  } else if (task.priority === "medium") {
    priorityEmoji = "🎯";
    colorId = "5"; // Banana (Yellow)
  }

  const completionStatus = task.isCompleted ? " [COMPLETED]" : "";
  const summary = `${priorityEmoji}${completionStatus} DEADLINE: ${task.title}`;

  // Formulate a structured and clean markdown-like description
  const description = [
    `🎯 TITLE: ${task.title}`,
    `🗂️ CATEGORY: ${task.category ? task.category.toUpperCase() : "OTHER"}`,
    `⚡ PRIORITY: ${task.priority ? task.priority.toUpperCase() : "MEDIUM"}`,
    `⏱️ ESTIMATED EFFORT: ${durationMinutes} minutes`,
    task.aiScore ? `🔥 COGNITIVE URGENCY SCORE: ${task.aiScore}/100` : null,
    task.aiRecommendation ? `🧠 AI ACTION RECOMMENDATION:\n${task.aiRecommendation}` : null,
    task.notes ? `📝 NOTES:\n${task.notes}` : null,
    `\n---\nGenerated by Clutch Workspace. Ensure high-focus, eliminate distractions, and shield your browser tab.`,
  ]
    .filter(Boolean)
    .join("\n\n");

  // Configured default reminders based on task priority
  const minutesBefore = task.priority === "high" ? 60 : 30;

  return {
    summary,
    description,
    start: {
      dateTime: startISO,
      timeZone,
    },
    end: {
      dateTime: endISO,
      timeZone,
    },
    colorId,
    reminders: {
      useDefault: false,
      overrides: [
        { method: "popup", minutes: minutesBefore },
        { method: "popup", minutes: 15 },
      ],
    },
  };
}

/**
 * Transforms an ItineraryItem (schedule block) into a Google Calendar Event structure.
 * Handles parsing "HH:MM - HH:MM" strings into valid dates on 2026-06-24.
 * 
 * @param block The itinerary item schedule block
 * @param baseDate ISO date string or "YYYY-MM-DD" representing the schedule date
 * @param timeZone Optional IANA time zone identifier
 * @returns GoogleCalendarEvent
 */
export function transformItineraryToCalendarEvent(
  block: ItineraryItem,
  baseDate = "2026-06-24",
  timeZone = "America/Los_Angeles"
): GoogleCalendarEvent | null {
  try {
    const timeParts = block.time.split("-");
    if (timeParts.length !== 2) return null;

    const startStr = timeParts[0].trim();
    const endStr = timeParts[1].trim();

    // Parse baseDate to clean "YYYY-MM-DD" string
    const formattedBaseDate = baseDate.includes("T") ? baseDate.split("T")[0] : baseDate;

    // Use full date constructor with America/Los_Angeles offset for correct parser formatting
    // If running in node, constructing ISO string with timezone offset:
    const startDateTimeStr = `${formattedBaseDate}T${startStr.padStart(5, "0")}:00`;
    const endDateTimeStr = `${formattedBaseDate}T${endStr.padStart(5, "0")}:00`;

    // To parse correctly with custom IANA timezone offset, we parse and apply relative UTC conversion,
    // or format them as local-with-timezone for Google Calendar API.
    // The Google API prefers standard ISO with offset, e.g. "2026-06-24T09:00:00-07:00".
    // Let's format them safely.
    // Assuming PD/ST offset -07:00 for the app's default America/Los_Angeles context:
    const startISO = `${startDateTimeStr}-07:00`;
    const endISO = `${endDateTimeStr}-07:00`;

    const isRelax = !!block.isBuffer;
    const summary = isRelax ? `☕ REST: ${block.task}` : `🎯 FOCUS: ${block.task}`;
    const colorId = isRelax ? "10" : "9"; // Basil (green) for rest, Blueberry (blue) for focus

    const description = [
      `📅 DAILY ITINERARY FOCUS BLOCK`,
      `🕒 SCHEDULED: ${block.time}`,
      `💡 TASK: ${block.task}`,
      block.focusTip ? `🛡️ COGNITIVE SHIELD TIP:\n${block.focusTip}` : null,
      `\n---\nGenerated by Clutch. Auto-sync locked in.`,
    ]
      .filter(Boolean)
      .join("\n\n");

    return {
      summary,
      description,
      start: {
        dateTime: startISO,
        timeZone,
      },
      end: {
        dateTime: endISO,
        timeZone,
      },
      colorId,
      reminders: {
        useDefault: false,
        overrides: [{ method: "popup", minutes: 5 }],
      },
    };
  } catch (err) {
    console.error("Error transforming itinerary block to calendar event:", err);
    return null;
  }
}
